-- Add columns to store code reviews on reflections
-- Reviews are tied to reflections, not standalone

ALTER TABLE public.reflections
ADD COLUMN IF NOT EXISTS review_content text,
ADD COLUMN IF NOT EXISTS review_suggestions jsonb,
ADD COLUMN IF NOT EXISTS review_requested_at timestamptz,
ADD COLUMN IF NOT EXISTS jot_suggested_review boolean DEFAULT false;

-- Add index for finding reflections with reviews
CREATE INDEX IF NOT EXISTS idx_reflections_review_requested 
ON public.reflections (review_requested_at) 
WHERE review_requested_at IS NOT NULL;

COMMENT ON COLUMN public.reflections.review_content IS 'Deep code review generated by agent';
COMMENT ON COLUMN public.reflections.review_suggestions IS 'Structured suggestions from the review';
COMMENT ON COLUMN public.reflections.review_requested_at IS 'When the user requested a deep review';
COMMENT ON COLUMN public.reflections.jot_suggested_review IS 'Whether jot proactively suggested a review';
